export enum currentWeatherTypes {
  FETCH_CURRENT_WEATHER_REQUEST = 'FETCH_CURRENT_WEATHER_REQUEST',
  FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS',
  FETCH_CURRENT_WEATHER_FAILURE = 'FETCH_CURRENT_WEATHER_FAILURE',
}
