export enum futureWeatherTypes {
  FETCH_FUTURE_WEATHER_REQUEST = 'FETCH_FUTURE_WEATHER_REQUEST',
  FETCH_FUTURE_WEATHER_SUCCESS = 'FETCH_FUTURE_WEATHER_SUCCESS',
  FETCH_FUTURE_WEATHER_FAILURE = 'FETCH_FUTURE_WEATHER_FAILURE',
}
